// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5TX-T_eP6hRFLQ_bWe_WRu1Ly4C86fXM',
    appId: '1:960662580539:web:fdee70f102f956ec0c1b1e',
    messagingSenderId: '960662580539',
    projectId: 'intdesproj-fa3ee',
    authDomain: 'intdesproj-fa3ee.firebaseapp.com',
    databaseURL: 'https://intdesproj-fa3ee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intdesproj-fa3ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBueHc2mpNkfg0p4G2Y5SpUW_0S6fQVCuc',
    appId: '1:960662580539:android:571538ee313d20c60c1b1e',
    messagingSenderId: '960662580539',
    projectId: 'intdesproj-fa3ee',
    databaseURL: 'https://intdesproj-fa3ee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intdesproj-fa3ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDsR-JrJYBq-jNIqXxQaVT_Wx8sxTQo-0',
    appId: '1:960662580539:ios:51f3475f072d85ac0c1b1e',
    messagingSenderId: '960662580539',
    projectId: 'intdesproj-fa3ee',
    databaseURL: 'https://intdesproj-fa3ee-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intdesproj-fa3ee.appspot.com',
    iosClientId: '960662580539-m0mrcv10p4tln7afgv8sq63ivmdg11gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.indesproj',
  );
}
